const config = { 
    UtmSource: "google_brand",
    UtmMedium: "ppc",
    UtmTerm: "policybazaar",
    UtmCampaign: "PolicyBazaar00Policybazaar",
    CJType: 1,
    LeadSource: "PB",
    apiEnquiryId: "https://traveldev.policybazaar.com/prequote/serverhelper",
    // apiMarketingCampaign: "https://travel.policybazaar.com/Service/MarketingCampaign",
    apiIpLocator: "https://iplocator.policybazaar.com/iplocation",
    baseUrl: "https://travelapiv2dev.policybazaar.com/",
    tempUrl: "https://traveldev.policybazaar.com/newapi/",
    // http://travelapiv2dev.policybazaar.com/quote/SaveQuoteData 
    iPLocator: 'https://traveldev.policybazaar.com/api/IsInternalIP/',
    passportURL:"https://api.merak.ai/v1/text-recognition/ktc/extract?key=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyNSwiZW1haWwiOiJheXVzaGFAcG9saWN5YmF6YWFyLmNvbSIsIm9yZ2FuaXphdGlvbl9pZCI6NSwiaWF0IjoxNTQzMzI1ODQxfQ.Yd3esLMI420wipsUYktJdC4d3rPTaTtgDcVoq0bQ0wI",
    endpoints: {
        init: 'preQuote/InitPreQuoteV2',
        savePreQuote: 'preQuote/SavePreQuoteV2',
        getQuotes: 'GetQuotes',
        getStep1:'proposal/GetStep1V2',
        modifyStep1Data:'proposal/ModifyStep1V2',
        saveQuotesSelection: 'SaveQuotesSelection',
        getStep2:'proposal/GetStep2V2',
        modifyProposer:'proposal/ModifyProposer',
        modifyInsuredMember:'proposal/ModifyInsuredMember',
        modifyStep2Data:'proposal/ModifyStep2V2',
        GetTripSummary :'Quote/GetTripSummary',
        saveQuotes: 'quote/SaveQuoteV2',
        // getQuoteData: 'quote/GetQuoteData',
        getQuoteData: 'quote/GetQuoteV2',
        saveQuotesSelection:'SaveQuotesSelection',
        getPreQuote: 'prequote/GetPreQuoteV2',
        getCheckoutData: 'Checkout/GetCheckoutDataV2',
        getInsurerProposal: 'checkout/GetInsurerProposals',
        initiatePG: 'checkout/InitiatePG',
        logActiveQuotes:'Support/LogQuotes',
        continueCJ:'misc/GetContinueURL',
        savePageTracker: 'misc/SavePageTracker',
        emailQuote: 'Quote/EmailQuote',
        saveFilters:'Quote/SaveFilters',
        createBookings:'Quote/CreateBookings'
    }
}
export default config;
